class_name EffectKeys
extends RefCounted

const INF_CAP := 99999999

const PRIMARY_STATS := [
	"stat_max_hp",
	"stat_hp_regeneration",
	"stat_lifesteal",
	"stat_percent_damage",
	"stat_melee_damage",
	"stat_ranged_damage",
	"stat_elemental_damage",
	"stat_engineering",
	"stat_attack_speed",
	"stat_crit_chance",
	"stat_range",
	"stat_armor",
	"stat_dodge",
	"stat_speed",
	"stat_luck",
	"stat_harvesting",
]

const CAPPED_STATS := {
	"stat_max_hp": "hp_cap",
	"stat_speed": "speed_cap",
	"stat_dodge": "dodge_cap",
	"stat_crit_chance": "crit_chance_cap",
}

const DEFAULTS := {
	"stat_max_hp": 10,
	"stat_armor": 0,
	"stat_crit_chance": 0,
	"stat_luck": 0,
	"stat_attack_speed": 0,
	"stat_elemental_damage": 0,
	"stat_hp_regeneration": 0,
	"stat_lifesteal": 0,
	"stat_melee_damage": 0,
	"stat_percent_damage": 0,
	"stat_dodge": 0,
	"stat_engineering": 0,
	"stat_range": 0,
	"stat_ranged_damage": 0,
	"stat_speed": 0,
	"stat_harvesting": 0,
	"xp_gain": 0,
	"number_of_enemies": 0,
	"consumable_heal": 0,
	"burning_cooldown_reduction": 0,
	"burning_cooldown_increase": 0,
	"burning_spread": 0,
	"piercing": 0,
	"piercing_damage": 0,
	"pickup_range": 0,
	"chance_double_gold": 0,
	"bounce": 0,
	"bounce_damage": 0,
	"heal_when_pickup_gold": 0,
	"item_box_gold": 0,
	"knockback": 0,
	"hp_cap": INF_CAP,
	"speed_cap": INF_CAP,
	"lose_hp_per_second": 0,
	"map_size": 0,
	"dodge_cap": 60,
	"crit_chance_cap": INF_CAP,
	"gold_drops": 0,
	"enemy_health": 0,
	"enemy_damage": 0,
	"enemy_speed": 0,
	"boss_strength": 0,
	"explosion_size": 0,
	"explosion_damage": 0,
	"damage_against_bosses": 0,
	"weapon_slot": 6,
	"items_price": 0,
	"reroll_price": 0,
	"harvesting_growth": 5,
	"hit_protection": 0,
	"weapons_price": 0,
	"structure_attack_speed": 0,
	"structure_percent_damage": 0,
	"structure_range": 0,
	"enemy_gold_drops": 0,
	"neutral_gold_drops": 0,
	"accuracy": 0,
	"projectiles": 0,
	"gain_stat_max_hp": 0,
	"gain_stat_armor": 0,
	"gain_stat_crit_chance": 0,
	"gain_stat_luck": 0,
	"gain_stat_attack_speed": 0,
	"gain_stat_elemental_damage": 0,
	"gain_stat_hp_regeneration": 0,
	"gain_stat_lifesteal": 0,
	"gain_stat_melee_damage": 0,
	"gain_stat_percent_damage": 0,
	"gain_stat_dodge": 0,
	"gain_stat_engineering": 0,
	"gain_stat_range": 0,
	"gain_stat_ranged_damage": 0,
	"gain_stat_speed": 0,
	"gain_stat_harvesting": 0,
	"gain_stat_curse": 0,
	"gain_explosion_damage": 0,
	"gain_piercing_damage": 0,
	"gain_bounce_damage": 0,
	"gain_damage_against_bosses": 0,
	"no_melee_weapons": 0,
	"no_ranged_weapons": 0,
	"no_duplicate_weapons": 0,
	"hp_start_wave": 100,
	"hp_start_next_wave": 100,
	"pacifist": 0,
	"cryptid": 0,
	"torture": 0,
	"recycling_gains": 0,
	"one_shot_trees": 0,
	"gain_pct_gold_start_wave": 0,
	"max_ranged_weapons": 999,
	"max_melee_weapons": 999,
	"group_structures": 0,
	"can_attack_while_moving": 1,
	"trees": 0,
	"trees_start_wave": 0,
	"min_weapon_tier": 0,
	"max_weapon_tier": 99,
	"hp_shop": 0,
	"free_rerolls": 0,
	"instant_gold_attracting": 0,
	"double_boss": 0,
	"wandering_bots": 0,
	"can_burn_enemies": 1,
	"danger_enemy_health": 0,
	"danger_enemy_damage": 0,
	"heal_on_crit_kill": 0,
	"heal_on_kill": 0,
	"minimum_weapons_in_shop": 0,
	"destroy_weapons": 0,
	"extra_loot_aliens_next_wave": 0,
	"extra_loot_aliens": 0,
	"special_enemies_last_wave": 0,
	"no_heal": 0,
	"tree_turrets": 0,
	"upgraded_baits": 0,
	"burning_enemy_speed": 0,
	"weapon_slot_upgrades": 0,
	"next_level_xp_needed": 0,
	"all_weapons_count_for_sets": 0,
	"structures_can_crit": 0,
	"pierce_on_crit": 0,
	"bounce_on_crit": 0,
	"consumable_heal_over_time": 0,
	"lock_current_weapons": 0,
	"knockback_aura": 0,
	"level_upgrades_modifications": 0,
	"enemy_fruit_drops": 0,
	"poisoned_fruit": 0,
	"gold_on_cursed_enemy_kill": 0,
	"loot_alien_speed": 0,
	"bonus_non_elemental_damage_against_burning_targets": 0,
	"item_steals": 0,
	"item_steals_spawns_random_elite": 0,
	"disable_item_locking": 0,
	"crate_chance": 0,
	"loot_alien_chance": 0,
	"max_turret_count": INF_CAP,
	"materials_per_living_enemy": 0,
	"negative_knockback": 0,
	"curse_locked_items": 0,
	"reload_when_pickup_gold": 0,
	"increase_material_value": 0,
	"stronger_elites_on_kill": 0,
	"stronger_loot_aliens_on_kill": 0,
	"item_hourglass": 0,
	"extra_elite_next_wave_chance": 0,
	"used_item_locking": 0,
	"stat_double_lifesteal_bonus": 0,
	"stat_jellyshield_count": 0,
	"stat_beast_master_effect": 0,
	"stat_boosted_wanted_item_tag": 0,
	"stat_has_lootworm": 0,
	"dmg_when_pickup_gold": [],
	"dmg_when_death": [],
	"dmg_when_heal": [],
	"dmg_on_dodge": [],
	"heal_on_dodge": [],
	"remove_speed": [],
	"starting_item": [],
	"cursed_starting_item": [],
	"starting_weapon": [],
	"cursed_starting_weapon": [],
	"projectiles_on_death": [],
	"burning_enemy_hp_percent_damage": [],
	"weapon_class_bonus": [],
	"unique_weapon_effects": [],
	"additional_weapon_effects": [],
	"tier_iv_weapon_effects": [],
	"tier_i_weapon_effects": [],
	"gold_on_crit_kill": [],
	"temp_stats_while_not_moving": [],
	"temp_stats_while_moving": [],
	"temp_stats_on_hit": [],
	"stats_end_of_wave": [],
	"stat_links": [],
	"structures": [],
	"explode_on_hit": [],
	"explode_when_below_hp": [],
	"convert_stats_end_of_wave": [],
	"explode_on_death": [],
	"alien_eyes": [],
	"upgrade_random_weapon": [],
	"extra_enemies_next_wave": [],
	"stats_next_wave": [],
	"consumable_stats_while_max": [],
	"temp_consumable_stats_while_max": [],
	"explode_on_consumable": [],
	"explode_on_consumable_burning": [],
	"structures_cooldown_reduction": [],
	"convert_stats_half_wave": [],
	"stats_on_level_up": [],
	"temp_stats_on_dodge": [],
	"stats_below_half_health": [],
	"guaranteed_shop_items": [],
	"specific_items_price": [],
	"minimum_weapon_cooldowns": [],
	"maximum_weapon_cooldowns": [],
	"weapon_scaling_stats": [],
	"slow_on_hit": [],
	"enemy_percent_damage_taken": [],
	"gain_stat_for_equipped_item_with_stat": [],
	"landmines_on_death_chance": [],
	"temp_stats_on_structure_crit": [],
	"gain_stat_for_every_step_after_equip": [],
	"decaying_stats_on_consumable": [],
	"decaying_stats_on_hit": [],
	"temp_stats_per_interval": [],
	"stats_on_fruit": [],
	"duplicate_item": [],
	"gain_stat_when_attack_killed_enemies": [],
	"extra_item_in_crate": [],
	"bonus_damage_against_targets_above_hp": [],
	"bonus_damage_against_targets_below_hp": [],
	"modify_every_x_projectile": [],
	"giant_crit_damage": [],
	"bonus_weapon_class_damage_against_cursed_enemies": [],
	"item_steals_spawns_enemy": [],
	"explode_on_overkill": [],
	"gain_stat_for_duplicate_items": [],
	"convert_bonus_gold": [],
	"remove_shop_items": [],
	"charm_on_hit": [],
	"weapon_type_bonus": [],
	"scale_materials_with_distance": [],
	"increase_tier_on_reroll": [],
	"gain_stats_on_reroll": [],
	"hp_regen_bonus": [],
	"gain_random_primary_stats_on_go_to_next_wave": [],
	"gain_stat_for_killed_enemies_while_burning": [],
	"stat_pets": [],
	"burn_chance": {},
	"extra_enemies_at_wave": {},
	"extra_loot_aliens_at_wave": {},
}

static func defaults() -> Dictionary:
	var result := {}
	for key in DEFAULTS.keys():
		result[key] = _duplicate_default(DEFAULTS[key])
	return result

static func key_count() -> int:
	return DEFAULTS.size()

static func has_key(key: String) -> bool:
	return DEFAULTS.has(key)

static func _duplicate_default(value: Variant) -> Variant:
	if value is Array or value is Dictionary:
		return value.duplicate(true)
	return value

